---

hostname: db1.staging

#zsh
users:
  - username: patte
    oh_my_zsh:
      theme: r_nonproduction
      plugins:
        - git
  - username: root
    oh_my_zsh:
      theme: r_nonproduction
  - username: postgres
    oh_my_zsh:
      theme: r_nonproduction
      plugins:
        - postgres

#postgres
# IP: barman
postgresql_pg_hba_custom:
  - type: host
    database: replication
    user: streaming_barman
    address: "159.100.253.185/32"
    method: "trust"
  - type: host
    database: all
    user: barman
    address: "159.100.253.185/32"
    method: "trust"

postgresql_archive_command: 'rsync -ap -e "ssh -o StrictHostKeyChecking=no" --bwlimit=1000 %p barman@barman.project-r.construction:/var/lib/barman/db1.staging/incoming/%f'

postgresql_ssh_key_file: "files/id_rsa_db1.staging"
postgresql_ssh_pub_key_file: "files/id_rsa_db1.staging.pub"
