apiVersion: v1
kind: ReplicationController
metadata:
  name: fileserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: static-files
            mountPath: /usr/share/nginx/html
        #volumeMounts:
        #  - name: config-volume
        #    mountPath: /etc/nginx/conf.d
      volumes:
      - name: static-files
        configMap:
          name: static-files
      #- name: config-volume
      #  configMap:
      #    name: fileserver-config
