nginx:
  image: nginx:latest
  restart: always
  ports: 
    - "80:80"
    - "443:443"
  volumes:
    - /docker/etc/deployer/nginx/conf.d/:/etc/nginx/conf.d
    - /etc/letsencrypt/:/etc/letsencrypt:ro
