apiVersion: v1
kind: ReplicationController
metadata:
  name: whoami
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
