- name: postgres-client for Project R
  hosts: postgres-client
  become: true
  vars:
    postgresql_version: 9.6
    postgresql_apt_key_id: ACCC4CF8
    postgresql_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    postgresql_apt_repository: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main {{postgresql_version}}'
    # Pin-Priority of PGDG repository
    postgresql_apt_pin_priority: 500
    postgresql_locale_parts:
      - 'en_US' # Locale
      - 'UTF-8' # Encoding
    postgresql_locale: "{{ postgresql_locale_parts | join('.') }}"
    postgresql_env:
      LC_ALL: "{{ postgresql_locale }}"
      LC_LCTYPE: "{{ postgresql_locale }}"
  tasks:
    # The standard ca-certs are needed because  without them apt_key will fail to
    # validate www.postgresql.org (or probably any other source).
    - name: PostgreSQL | Make sure the CA certificates are available
      apt:
        pkg: ca-certificates
        state: present

    - name: PostgreSQL | Add PostgreSQL repository apt-key
      apt_key:
        id: "{{ postgresql_apt_key_id }}"
        url: "{{ postgresql_apt_key_url }}"
        state: present
      when: postgresql_apt_key_url and postgresql_apt_key_id

    - name: PostgreSQL | Add PostgreSQL repository
      apt_repository:
        repo: "{{ postgresql_apt_repository }}"
        state: present
      when: postgresql_apt_repository | default('') != ''

    - name: PostgreSQL | Add PostgreSQL repository preferences
      template:
        src: etc_apt_preferences.d_apt_postgresql_org_pub_repos_apt.pref.j2
        dest: /etc/apt/preferences.d/apt_postgresql_org_pub_repos_apt.pref
      when: postgresql_apt_pin_priority

    - name: PostgreSQL | Make sure the dependencies are installed
      apt:
        pkg: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
      with_items: ["python-psycopg2", "python-pycurl", "locales"]

    - name: PostgreSQL | Install PostgreSQL
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
      environment: "{{postgresql_env}}"
      with_items:
        - "postgresql-client-{{postgresql_version}}"
