db:
  image: mattermost/mattermost-prod-db
  restart: always
  volumes:
    - /docker/data/mattermost/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  # uncomment the following to enable backup
  #environment:
  #  - AWS_ACCESS_KEY_ID=XXXX
  #  - AWS_SECRET_ACCESS_KEY=XXXX
  #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
  #  - AWS_REGION=us-east-1
app:
  image: mattermost/mattermost-prod-app
  links:
    - db:db
  restart: always
  volumes:
    - /docker/data/mattermost/app/mattermost/config:/mattermost/config:rw
    - /docker/data/mattermost/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
web:
  image: mattermost/mattermost-prod-web
  ports:
    - "80:80"
    - "443:443"
  links:
    - app:app
  restart: always
  volumes:
      # This directory must have cert files
    - /etc/letsencrypt/live/mattermost.project-r.construction/fullchain.pem:/cert/cert.pem:ro
    - /etc/letsencrypt/live/mattermost.project-r.construction/privkey.pem:/cert/key-no-password.pem:ro
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MATTERMOST_ENABLE_SSL=true
    - PLATFORM_PORT_80_TCP_PORT=80
